services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: aymoose
      POSTGRES_PASSWORD: 5ay58MOO58se8
      POSTGRES_DB: server
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U server"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql/init/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - db_network

networks:
  db_network:
    driver: bridge
